// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEvent(arg1:models.Event):Promise<models.Event>;

export function DeleteEvent(arg1:models.Event):Promise<models.Event>;

export function DismissEvent(arg1:models.Event):Promise<models.Event>;

export function GetAllEvents():Promise<Array<models.Event>>;

export function PrintEventStruct(arg1:models.Event):Promise<void>;

export function UpdateEvent(arg1:models.Event):Promise<models.Event>;
