// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1) {
  return window['go']['main']['App']['CreateEvent'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DismissEvent(arg1) {
  return window['go']['main']['App']['DismissEvent'](arg1);
}

export function GetAllEvents() {
  return window['go']['main']['App']['GetAllEvents']();
}

export function PrintEventStruct(arg1) {
  return window['go']['main']['App']['PrintEventStruct'](arg1);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}
